apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: wthfabmedicalacr.azurecr.io/content-api:v1
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
        ports:
        - containerPort: 3001