apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api-v2
  labels:
    app: content-api-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-api-v2
  template:
    metadata:
      labels:
        app: content-api-v2
    spec:
      containers:
      - name: content-api-v2
        image: wthfabmedicalacr.azurecr.io/content-api:v2
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 3001